/**
 * Build REPORT.md - Analysis report for generated rules
 */

export interface SegmentReport {
  prefix: string;
  status: 'success' | 'skipped' | 'failed';
  reason?: string; // skip/fail reason
  type?: 'template-based' | 'decomposed' | 'small-segment';
  lines?: number;
  filename?: string;
}

export interface AnalysisReport {
  projectPath: string;
  totalFiles: number;
  totalSegments: number;
  analyzedSegments: number;
  segmentReports: SegmentReport[];
  timestamp: string;
}

/**
 * Generate REPORT.md content based on analysis results
 */
export function buildReportGuide(report: AnalysisReport): string {
  const { projectPath, totalFiles, totalSegments, analyzedSegments, segmentReports, timestamp } = report;

  // Separate by status
  const successReports = segmentReports.filter(s => s.status === 'success');
  const skippedReports = segmentReports.filter(s => s.status === 'skipped');
  const failedReports = segmentReports.filter(s => s.status === 'failed');

  // Find long guides (>200 lines)
  const longGuides = successReports.filter(s => s.lines && s.lines > 200);

  // Group by type
  const templateBased = successReports.filter(s => s.type === 'template-based');
  const decomposed = successReports.filter(s => s.type === 'decomposed');

  return `# RepoRules 분석 리포트

> 이 리포트는 RepoRules의 작업에 대한 리포트입니다.
> 코드 제작과는 무관하니, 읽고 지우셔도 무방합니다.

생성 일시: ${timestamp}
프로젝트: ${projectPath}

---

## 프로젝트 구조 분석

${totalSegments <= 1 ?
`해당 프로젝트는 여러 모듈(구획)로 만들어진 프로젝트가 아니라 단일 모듈(구획)로 판단됩니다.

- 총 파일 수: ${totalFiles}
- 생성된 규칙: ${successReports.length}개` :
`해당 프로젝트는 ${totalSegments}개의 구획(모듈)로 나눠서 분석합니다:

${segmentReports.map(s => {
  const typeLabel = s.status === 'success' ? s.type : s.status === 'skipped' ? 'flat' : 'failed';
  const warning = s.lines && s.lines > 200 ? ' [200줄 초과]' : '';
  return `- ${s.prefix} (${typeLabel})${warning}`;
}).join('\n')}

- 총 파일 수: ${totalFiles}
- 생성된 규칙: ${successReports.length}개`}

---

## 모듈 구분

### flat
특정한 패턴, 규칙을 찾을 수 없는 모듈입니다. global 규칙만을 따릅니다.

${skippedReports.length === 0 ? '(해당 없음)' : skippedReports.map(s => `- ${s.prefix}`).join('\n')}

### template
DDD, Hexagonal 등 도메인 혹은 항목을 나타내는 폴더 하위에 해당 목적의 코드를 배치하는 구조입니다.

${templateBased.length === 0 ? '(해당 없음)' : templateBased.map(s => `- ${s.prefix}`).join('\n')}

### decomposed
template은 아니지만, 반복되는 패턴과 규칙이 있는 경우 두드러지는 것을 감지해서 정리합니다.

${decomposed.length === 0 ? '(해당 없음)' : decomposed.map(s => `- ${s.prefix}`).join('\n')}

---

## 주의사항

${longGuides.length === 0 ? '모든 가이드가 200줄 이하입니다.' : `### 200줄 초과 가이드 (${longGuides.length}개)

${longGuides.map(s => `- \`${s.filename}\`: ${s.lines}줄`).join('\n')}

압축 목표는 150-200줄이지만, 패턴이 많거나 복잡한 구조인 경우 초과할 수 있습니다.
가이드를 직접 수정하여 불필요한 패턴을 제거하는 것을 권장합니다.`}

${failedReports.length > 0 ? `

### 실패한 세그먼트 (${failedReports.length}개)

${failedReports.map(s => `- ${s.prefix}`).join('\n')}

LLM 오류 또는 타임아웃으로 생성에 실패했습니다. 재실행을 권장합니다.` : ''}

---

## 가이드 활용 팁

### 생성된 규칙 파일 목록

${successReports.length > 0 ? successReports.map(s => {
  return `- \`rules/${s.filename}\``;
}).join('\n') : '생성된 규칙 파일이 없습니다.'}

### 잘못된 규칙은 없는 규칙만 못합니다

초안을 바탕으로 검수 후에 skills, rules, agent 프롬프트에 추가하는 것을 추천드립니다.

### 200줄 이상의 프롬프트

200줄 이상의 프롬프트는 불필요한 내용을 제거, 혹은 항목별 파일의 분리를 권장합니다.

---

## 구조가 개발자의 의식과 다른 경우

프로젝트 최상위 폴더에 \`.reporules.md\` 파일에 규칙을 적어주세요.

분석 단계의 스크립트가 해당 리소스를 참조합니다.

---

Generated by RepoRules v0.1.0
`;
}
