/**
 * Build USAGE.md guide for generated rules
 */

import { SkillEntry } from '../llm/generateSkills';

export interface RuleFileInfo {
  prefix: string;
  filename: string;
}

/**
 * Build file list section for USAGE.md
 */
function buildFileList(ruleFiles: RuleFileInfo[], hasGlobalRules: boolean): string {
  const fileList = [];

  if (hasGlobalRules) {
    fileList.push('- **global.md** - 전역 공통 규칙 (모든 파일에 적용)');
  }

  for (const file of ruleFiles) {
    const displayName = file.prefix.replace(/\/+$/, '').replace(/\//g, ' › ') || 'root';
    fileList.push(`- **${file.filename}** - ${displayName} 모듈 가이드`);
  }

  return fileList.join('\n');
}

/**
 * Build generated skills section
 */
function buildSkillsSection(skills: SkillEntry[]): string {
  if (skills.length === 0) {
    return '(생성된 skills 없음)';
  }

  return skills.map(s => `- **${s.title}.md**`).join('\n');
}

/**
 * Generate USAGE.md content based on generated rule files and skills
 */
export function buildUsageGuide(
  ruleFiles: RuleFileInfo[],
  hasGlobalRules: boolean,
  skills: SkillEntry[] = []
): string {
  const fileList = buildFileList(ruleFiles, hasGlobalRules);
  const skillsSection = buildSkillsSection(skills);

  return `# RepoRules 사용 가이드

RepoRules는 프로젝트의 패턴을 파악해서, 모듈·주요 패키지·반복되는 규칙을 문서화합니다.

**rules**: 경로별 코딩 패턴과 컨벤션. 코딩 에이전트가 해당 경로 작업 시 참고하도록 설정합니다.
**skills**: 도메인 추가·데이터 흐름 등 특정 작업의 단계별 가이드. 반복 작업을 자동화할 때 활용합니다.

각 파일을 사용하는 코딩 에이전트에 맞게 배치하세요.
- **Claude Code**: \`.claude/rules/\` 에 rules 배치, \`.claude/skills/\` 에 skills 배치
- **Cursor**: Cursor rules 폴더에 rules 배치

---

> **주의**
> 대표 파일을 샘플링해서 패턴을 추출하므로, 전체 코드에서 보이는 규칙이 일부 누락될 수 있습니다.
> 내용이 맞지 않거나 디테일 수정이 필요한 경우 코딩 에이전트로 직접 수정하세요. 골격으로 활용하시면 됩니다.

---

## 생성된 파일

### Rules
${fileList}

### Skills
${skillsSection}

---

Generated by [RepoRules](https://github.com/your-repo/reporules)
`;
}
